name: Tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: End to end tests
    # This job runs on Linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Yarn install
        run: yarn install
      - name: Check available browsers
        run: yarn testcafe -b
      - name: Yarn start
        run: yarn start &
      - name: Wait a bit
        run: sleep 60
      - name: Run the tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "--concurrent 10 chrome tests/test_home.js"
