name: Tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: End to end tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: checkout
        uses: actions/checkout@v2
      - name: what is running
        run: ps -ef
      - name: yarn install
        run: yarn install
      - name: yarn start
        run: yarn start &
      - name: service checkup
        run: node startService.js
      - name: check browsers
        run: yarn testcafe -b
      - name: run the tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests/test_home.js"
