name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: checkout
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn start
        run: yarn start& ; node startService.js
      - name: get some system printout
        run: set -ex; whoami ; pwd ; ls ; docker ps; node --version ; npm --version; yarn --version ; echo "done"
